INSERT IGNORE INTO book_catalog
    (catalog_book_id, title, author, genre, description, cover_url, isbn)
VALUES
    (1, 'Children of Captain Grant', 'Jules Verne', 'Adventure', 'A scattered family follows clues across oceans and continents.', NULL, NULL),
    (2, 'Twenty Thousand Leagues Under the Seas', 'Jules Verne', 'Adventure', 'A professor discovers the secrets and dangers of Captain Nemo''s submarine.', NULL, NULL),
    (3, 'The Mysterious Island', 'Jules Verne', 'Adventure', 'Castaways turn an unknown island into a home of invention and survival.', NULL, NULL),
    (4, 'Around the World in Eighty Days', 'Jules Verne', 'Adventure', 'A precise gentleman races time, chance, and geography to win a wager.', NULL, NULL),
    (5, 'Journey to the Center of the Earth', 'Jules Verne', 'Adventure', 'Explorers descend into a hidden world beneath the surface.', NULL, NULL),
    (6, 'The Hobbit', 'J.R.R. Tolkien', 'Fantasy', 'A reluctant traveler joins a quest filled with courage, riddles, and treasure.', NULL, '9780547928227'),
    (7, 'The Lord of the Rings', 'J.R.R. Tolkien', 'Fantasy', 'An epic journey tests friendship, mercy, and the burden of power.', NULL, NULL),
    (8, 'The Silmarillion', 'J.R.R. Tolkien', 'Fantasy', 'Myths of creation, rebellion, and ancient kingdoms shape Middle-earth.', NULL, NULL),
    (9, '1984', 'George Orwell', 'Dystopian', 'A controlled society turns language, memory, and truth into weapons.', NULL, '9780451524935'),
    (10, 'Animal Farm', 'George Orwell', 'Satire', 'A revolution on a farm becomes a sharp fable about power.', NULL, NULL),
    (11, 'Fahrenheit 451', 'Ray Bradbury', 'Science Fiction', 'A fireman in a book-burning world begins to question obedience.', NULL, NULL),
    (12, 'Dune', 'Frank Herbert', 'Science Fiction', 'Noble families, desert survival, and prophecy collide on Arrakis.', NULL, '9780441172719'),
    (13, 'Foundation', 'Isaac Asimov', 'Science Fiction', 'A hidden plan tries to shorten the darkness after a galactic empire falls.', NULL, NULL),
    (14, 'I, Robot', 'Isaac Asimov', 'Science Fiction', 'Linked stories explore machines, logic, and the limits of human command.', NULL, NULL),
    (15, 'The Martian Chronicles', 'Ray Bradbury', 'Science Fiction', 'Earth settlers carry hope and old mistakes to Mars.', NULL, NULL),
    (16, 'Brave New World', 'Aldous Huxley', 'Dystopian', 'Comfort and control hide the cost of a manufactured society.', NULL, NULL),
    (17, 'The War of the Worlds', 'H.G. Wells', 'Science Fiction', 'An invasion from Mars overturns human certainty and pride.', NULL, NULL),
    (18, 'The Time Machine', 'H.G. Wells', 'Science Fiction', 'A traveler leaps into the far future and finds civilization transformed.', NULL, NULL),
    (19, 'The Left Hand of Darkness', 'Ursula K. Le Guin', 'Science Fiction', 'A diplomat learns to see identity and loyalty through another culture.', NULL, NULL),
    (20, 'A Wizard of Earthsea', 'Ursula K. Le Guin', 'Fantasy', 'A young mage faces the shadow released by his own pride.', NULL, NULL),
    (21, 'Neuromancer', 'William Gibson', 'Science Fiction', 'A washed-up hacker is pulled into a dangerous job across cyberspace.', NULL, NULL),
    (22, 'Snow Crash', 'Neal Stephenson', 'Science Fiction', 'A courier and hacker chase a digital threat through a fractured future.', NULL, NULL),
    (23, 'The Hitchhiker''s Guide to the Galaxy', 'Douglas Adams', 'Science Fiction', 'An ordinary human is swept into a comic tour of the universe.', NULL, NULL),
    (24, 'The Name of the Wind', 'Patrick Rothfuss', 'Fantasy', 'A gifted storyteller recounts his rise through music, magic, and loss.', NULL, NULL),
    (25, 'The Way of Kings', 'Brandon Sanderson', 'Fantasy', 'Soldiers, scholars, and rulers face storms both natural and political.', NULL, NULL),
    (26, 'Mistborn: The Final Empire', 'Brandon Sanderson', 'Fantasy', 'A crew of rebels challenges an immortal ruler with daring and metal magic.', NULL, NULL),
    (27, 'The Three Musketeers', 'Alexandre Dumas', 'Adventure', 'A young swordsman finds loyalty, rivalry, and intrigue in royal France.', NULL, NULL),
    (28, 'Treasure Island', 'Robert Louis Stevenson', 'Adventure', 'A map, a ship, and a dangerous crew lead to buried treasure.', NULL, NULL),
    (29, 'Robinson Crusoe', 'Daniel Defoe', 'Adventure', 'A castaway survives years alone through discipline and invention.', NULL, NULL),
    (30, 'Moby-Dick', 'Herman Melville', 'Novel', 'A whaling voyage becomes an obsession with nature, fate, and revenge.', NULL, NULL),
    (31, 'Pride and Prejudice', 'Jane Austen', 'Novel', 'Wit and first impressions shape a story of family, class, and love.', NULL, NULL),
    (32, 'Jane Eyre', 'Charlotte Bronte', 'Novel', 'An independent governess searches for dignity, belonging, and truth.', NULL, NULL),
    (33, 'Wuthering Heights', 'Emily Bronte', 'Novel', 'A stormy tale of passion, resentment, and haunted memory.', NULL, NULL),
    (34, 'Crime and Punishment', 'Fyodor Dostoevsky', 'Novel', 'A desperate act forces a student into guilt, fear, and moral reckoning.', NULL, NULL),
    (35, 'The Brothers Karamazov', 'Fyodor Dostoevsky', 'Novel', 'A divided family becomes the center of faith, doubt, and responsibility.', NULL, NULL),
    (36, 'War and Peace', 'Leo Tolstoy', 'Novel', 'Private lives unfold against the vast movement of history and war.', NULL, NULL),
    (37, 'Anna Karenina', 'Leo Tolstoy', 'Novel', 'Love, society, and conscience collide in a searching family drama.', NULL, NULL),
    (38, 'The Stranger', 'Albert Camus', 'Philosophy', 'A detached man faces judgment in a world that demands meaning.', NULL, NULL),
    (39, 'The Plague', 'Albert Camus', 'Novel', 'A sealed city reveals courage, fear, and solidarity during crisis.', NULL, NULL),
    (40, 'Siddhartha', 'Hermann Hesse', 'Philosophy', 'A seeker follows his own path through wisdom, desire, and stillness.', NULL, NULL),
    (41, 'Meditations', 'Marcus Aurelius', 'Philosophy', 'Private reflections turn discipline and humility into daily practice.', NULL, NULL),
    (42, 'The Republic', 'Plato', 'Philosophy', 'A dialogue asks what justice is and how a society should be ordered.', NULL, NULL),
    (43, 'Beyond Good and Evil', 'Friedrich Nietzsche', 'Philosophy', 'A provocative challenge to inherited morals and comfortable certainty.', NULL, NULL),
    (44, 'Clean Code', 'Robert C. Martin', 'Programming', 'Practical guidance for writing code that is easier to read and change.', NULL, '9780132350884'),
    (45, 'Effective Java', 'Joshua Bloch', 'Programming', 'Focused advice for using Java clearly, safely, and idiomatically.', NULL, '9780134685991'),
    (46, 'Design Patterns', 'Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides', 'Programming', 'Reusable object-oriented patterns for common design problems.', NULL, '9780201633610'),
    (47, 'The Pragmatic Programmer', 'Andrew Hunt, David Thomas', 'Programming', 'A practical handbook for improving craft, habits, and engineering judgment.', NULL, NULL),
    (48, 'Refactoring', 'Martin Fowler', 'Programming', 'A catalog of techniques for improving code structure without changing behavior.', NULL, NULL),
    (49, 'Domain-Driven Design', 'Eric Evans', 'Programming', 'An approach to modeling complex software around business language.', NULL, NULL),
    (50, 'Code Complete', 'Steve McConnell', 'Programming', 'A broad guide to construction practices that improve software quality.', NULL, NULL);
